name: Golang CI

on:
    push:
        branches:
            - master

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup Go
                uses: actions/setup-go@v2
                with:
                    go-version: '1.22'

            -   name: Run tests
                run: go test ./...

            -   name: Build
                run: go build -o myapp .