name: Angular CI

on:
    push:
        branches:
            - master

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup Node.js
                uses: actions/setup-node@v2
                with:
                    node-version: '20.x'

            -   name: Install dependencies
                run: |
                    cd frontend
                    npm install
                    npm run test:headless
                    npm run build:prod